apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus
  namespace: prometheus
spec:
  type: NodePort
  selector:
    prometheus: prometheus-kube-prometheus-prometheus
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30008
